In [23]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sklearn import preprocessing, svm 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression 

In [24]:
df = pd.read_csv('a - Sheet1.csv') 
print(df.shape)
df.describe().transpose()

(395, 3)


count       mean       std  min  25%   50%   75%   max
G1  395.0  10.908861  3.319195  3.0  8.0  11.0  13.0  19.0
G2  395.0  10.713924  3.761505  0.0  9.0  11.0  13.0  19.0
G3  395.0  10.415190  4.581443  0.0  8.0  11.0  14.0  20.0

In [17]:
print(df)


     G1  G2  G3
0     5   6   6
1     5   5   6
2     7   8  10
3    15  14  15
4     6  10  10
..   ..  ..  ..
390   9   9   9
391  14  16  16
392  10   8   7
393  11  12  10
394   8   9   9

[395 rows x 3 columns]


In [25]:
df.columns = ['G1', 'G2']

ValueError: Length mismatch: Expected axis has 3 elements, new values have 2 elements

In [19]:
X = df[predictors].values
y = df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=45)
print(X_train.shape); print(X_test.shape)



(316, 2)
(79, 2)


In [20]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(5,8,5), activation='relu', solver='adam', max_iter=1000)
mlp.fit(X_train,y_train.ravel())

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

C:\Users\bawej\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [21]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[20  0  0  0  0  3  0  5  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 6  0  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 7  0  0  0  0  9  0  9  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  4  0 16  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  0 33  7  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0 10 26  1  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1 10  5  5  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  5  2 16  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  7 12  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  3 23  3  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  7  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0  0]
 [ 0  0  0  0  0  0  0  0  0  0

C:\Users\bawej\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [22]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[ 7  0  0  1  0  2  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  5  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  4  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  2  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  1  5  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  4  3  2  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  4  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  4  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  4]]
              precision    recall  f1-score   support

           0       0.58      0.70      0.64        10
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3
           8       0.56      0.71      0.63         7
           9       0.00      0.00      0.00         6
          10       0.53      0.83      0.65 

In [1]:
from tkinter import *
from tkinter import messagebox #Always import messagebox seperately as it a sub module
top = Tk()

L1 = Label(top, text="ST_Name") 
L1.grid(row = 1, column = 1)
E1 = Entry(top, bd =5) #Attach text box to root frame. bd refers size of the border. default is 2 pixels
E1.grid(row = 1, column = 2)

L2 = Label(top, text="Mark 1") 
L2.grid(row = 2, column = 1) 
E2 = Entry(top, bd =5) 
E2.grid(row = 2, column = 2)

L3 = Label(top, text="Mark 2") 
L3.grid(row = 3, column = 1) 
E3 = Entry(top, bd =5) 
E3.grid(row = 3, column = 2)

L4 = Label(top, text="Mark 3") 
L4.grid(row = 4, column = 1)
E4 = Entry(top, bd =5) 
E4.grid(row = 4, column = 2)


def disp():
    m1 = int(E2.get())
    m2 = int(E3.get())
    m3 = int(E4.get())
    avg = (m1+m2+m3)/3
    if avg > 90:
        grd = "A"
    elif avg >=80 and avg <= 89:
        grd = "C"
    elif avg >=70 and avg <= 79:
        grd = "C"
    elif avg >=60 and avg <= 69:
        grd = "D"
    elif avg >=50 and avg <= 59:
        grd = "E"
    else:
        grd = "Fail"
    messagebox.showinfo("Your grade is",grd)
    
B1 = Button(top, text="display", command=disp)
B1.grid(row = 5, column = 2)

top.mainloop()
